### ISSUE TITLE
New population can get stuck if there is no pathway after spawning from town hall

### ISSUE THREAD

**Issue by Ruckamongus** [switchboy/IsoRTS#28] opened 2021-08-12 13:19 UTC
I spent some time playing today and noticed a few things that can be addressed:

- If you box in the spawn area of a town hall the units will never be able to move. you can select them but never redirect them.
![image](https://user-images.githubusercontent.com/1320779/129202823-0a560d49-1304-4565-abac-965de0de028b.png)
- When you select a large number of units the images in the bottom bar have odd orientation, sometimes outside of the bounds of the middle wooden rectangle texture (see bottom image).
- The edge scrolling continues to happen when the mouse leaves the game window.
- Sometimes the selection rectangle is... janky? It catches and misses some troops.
- There are times where the game stutters or freezes really badly for no apparent reason. It may be related to pathfinding. I'll run a profiler and see if I can figure this out soon.
- Pathfinding is sometimes unpredicatable. Troops may walk very long paths around obstacles that don't make much sense. I wonder if it's because troops refuse to walk on each other? I'll look more into this too.

This was fun though!
![image](https://user-images.githubusercontent.com/1320779/129203552-365fc63f-ee64-4906-ab89-c0225f40efc3.png)

**Comment by switchboy** [comment] 2021-08-12 20:41
> 
> 
> I spent some time playing today and noticed a few things that can be addressed:
> 
>     * If you box in the spawn area of a town hall the units will never be able to move. you can select them but never redirect them.
>       ![image](https://user-images.githubusercontent.com/1320779/129202823-0a560d49-1304-4565-abac-965de0de028b.png)

That's an unfortunate byproduct of units not walking on occupied tiles (since each tile can only handle one unit at a time with the current int array set-up. 

>     * When you select a large number of units the images in the bottom bar have odd orientation, sometimes outside of the bounds of the middle wooden rectangle texture (see bottom image).

This is now fixed. I tested it with a selection of more then 53 units 

> 
>     * The edge scrolling continues to happen when the mouse leaves the game window.
> 

This never botherd me but was an easy fix!

>     * Sometimes the selection rectangle is... janky? It catches and misses some troops.

The problem is that the selection box is selecting tiles not actors. It is on my list of things to change. Because it is also annoying when clicking on trees for gathering orders.

> 
>     * There are times where the game stutters or freezes really badly for no apparent reason. It may be related to pathfinding. I'll run a profiler and see if I can figure this out soon.
> 

It might be the AI running in a loop (if you did not disable the second player). or a lot of (unsuccessful) path finding at once. 

>     * Pathfinding is sometimes unpredicatable. Troops may walk very long paths around obstacles that don't make much sense. I wonder if it's because troops refuse to walk on each other? I'll look more into this too.
> 

Defenitly other actors blocking obvious paths and pathing only done when recieving a new order. Might be worth to do a periodic recheck when walking a long path to see if a shorter route ia available. Tip if you press S you can see the paths and 'blocked' tiles

> 
> This was fun though!
> ![image](https://user-images.githubusercontent.com/1320779/129203552-365fc63f-ee64-4906-ab89-c0225f40efc3.png)

**Comment by Ruckamongus** [comment] 2021-08-12 22:43
Pressing S was HUGE in understanding what was happening, thanks for showing me that! Embarassing I literally have the source code and didn't realize that was a feature. 😄

**Comment by switchboy** [comment] 2021-08-13 21:02
The new actor location framework now allows for actor to walk 'past' each other. This should remedy most awkward routes and actors getting stuck.

Also made selection of actors and objects by crude rect collision. This feels less janky. I might want to look into pixel perfect collision though, since this method is probably not going to work so well for buildings. since all the red coloring on the attached image will explain:
![image](https://user-images.githubusercontent.com/16579757/129417935-340659e1-99fe-4a62-b5b4-14a80d45c69b.png)

**Comment by switchboy** [comment] 2021-08-14 14:17
Implemented pixel perfect collision detection for building selection. I probably convert the actor and object selection to this style as well while I am at it.  But I think that wraps up most issues for now

**Closed** 2021-08-15 08:27 UTC
